title: BattMo
description: Open-source battery modeling ecosystem
url: "https://battmoteam.github.io"

# Use Odin as a remote theme
remote_theme: tylergaw/odin

# Optional theme settings
author: BattMoTeam
social_links:
  github: https://github.com/BattMoTeam

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
